// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCveAXCT8T-x0m_fzs641pYMj1vGjdlRyI',
    appId: '1:618965589215:web:f43c8e8ef28105ce699d6a',
    messagingSenderId: '618965589215',
    projectId: 'mentalwellness-27062024',
    authDomain: 'mentalwellness-27062024.firebaseapp.com',
    storageBucket: 'mentalwellness-27062024.appspot.com',
    measurementId: 'G-4Y3K9RG491',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvkRVYhpN5BoL-MeMLlPLjYXX5CNQ_2m4',
    appId: '1:618965589215:android:1290d63a5f153616699d6a',
    messagingSenderId: '618965589215',
    projectId: 'mentalwellness-27062024',
    storageBucket: 'mentalwellness-27062024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXExAbZRWn24o7uZxCxHF-lmtPXgbg7o',
    appId: '1:618965589215:ios:f92ef493712d0325699d6a',
    messagingSenderId: '618965589215',
    projectId: 'mentalwellness-27062024',
    storageBucket: 'mentalwellness-27062024.appspot.com',
    iosBundleId: 'com.example.mentalwellness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXExAbZRWn24o7uZxCxHF-lmtPXgbg7o',
    appId: '1:618965589215:ios:be6791a8789af872699d6a',
    messagingSenderId: '618965589215',
    projectId: 'mentalwellness-27062024',
    storageBucket: 'mentalwellness-27062024.appspot.com',
    iosBundleId: 'com.example.mentalwellness.RunnerTests',
  );
}
