// import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';

// // required: associates our `user.model.dart` with the code generated by Freezed
// part 'user.model.freezed.dart';
// // optional: Since our Person class is serializable, we must add this line.
// // But if Person was not serializable, we could skip it.
// part 'user.model.g.dart';

// @freezed
// class UserModel with _$UserModel {
//   const factory UserModel({
//     required String uid,
//     required String name,
//     required String imageUrl,
//     required DateTime createdAt,
//   }) = _UserModel;

//   factory UserModel.fromJson(Map<String, Object?> json)
//       => _$UserModelFromJson(json);
// }